### ISSUE TITLE
Second Time Adding - Duplicate Key

### ISSUE THREAD

**Issue by johndavemanuel** [bradtraversy/vue_crash_todolist#5]
Duplicate keys detected: '201'. This may cause an update error.

found in

```
---> <Todos> at src/components/Todos.vue
       <Home> at src/views/Home.vue
         <App> at src/App.vue
           <Root>
```

**Comment by nuno** [comment]
I think for this situation we still need to use uuid. Correct me if im wrong?
Thanks for the vue crash course, really good!

EDIT: nah . still the same...

**Comment by hogmansan** [comment]
I came to the same conclusion and i have not figured out a solution for this. It seems like the solution would need to increment the key for each added todo item, right? Would love to know how to implement this.

EDIT: It seems that the JSONPlaceholder only returns 201 as an id, since it only fakes POSTing.
From the documentation "Important: the resource will not be really created on the server but it will be faked as if. In other words, if you try to access a post using 101 as an id, you'll get a 404 error."
Someone explained this to me and showed me what is being returned and it makes sense for me now.

**Comment by colbyalbo** [comment]
Yeah, the JSON placeholder is going to return the same ID  with every POST request. Dont sweat that, you won't experience that with a real API, which will usually auto-increment.

**Comment by pagecow** [comment]
```
addTodo(newTodo) {
      const { title, completed } = newTodo;

      axios.post('http://jsonplaceholder.typicode.com/todos', {
        title,
        completed,
      })
        .then(res => {

        res.data.todos.forEach(e => {
          if(e.id === 201){
          console.log("201 error")
          } else {
          this.todos = [...this.todos, res.data]
        }})})
        .catch(err => console.log(err))

      this.todos = [...this.todos, newTodo];
    }
```

That fixed it for me.

**Comment by johndavemanuel** [comment]
ahh yes It is the API, probably we need to add condition just like yours

**Comment by shamwela** [comment]
> ```
> addTodo(newTodo) {
>       const { title, completed } = newTodo;
> 
>       axios.post('http://jsonplaceholder.typicode.com/todos', {
>         title,
>         completed,
>       })
>         .then(res => {
> 
>         res.data.todos.forEach(e => {
>           if(e.id === 201){
>           console.log("201 error")
>           } else {
>           this.todos = [...this.todos, res.data]
>         }})})
>         .catch(err => console.log(err))
> 
>       this.todos = [...this.todos, newTodo];
>     }
> ```
> 
> That fixed it for me.

What is 'e'?
![brave_y7nCiYTUHn](https://user-images.githubusercontent.com/62544170/89160217-ba8f8500-d596-11ea-8c2a-110856386833.png)
